---
steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--tag=gcr.io/${PROJECT_ID}/docker:latest'
  - '--file=Dockerfile-cloudbuild'
  - '.'
- name: 'gcr.io/${PROJECT_ID}/docker'
  args:
    - 'build'
    - '--tag=gcr.io/${PROJECT_ID}/gobuster:latest'
    - '--file=gobuster/Dockerfile'
    - '.'
- name: 'gcr.io/${PROJECT_ID}/docker'
  args:
    - 'build'
    - '--tag=gcr.io/${PROJECT_ID}/tshark:latest'
    - '--file=tshark/Dockerfile'
    - '.'
- name: 'gcr.io/${PROJECT_ID}/docker'
  args:
    - 'build'
    - '--tag=gcr.io/${PROJECT_ID}/beef:latest'
    - '--file=beef/Dockerfile'
    - '.'
images:
- 'gcr.io/${PROJECT_ID}/docker:latest'
- 'gcr.io/${PROJECT_ID}/gobuster:latest'
- 'gcr.io/${PROJECT_ID}/tshark:latest'
- 'gcr.io/${PROJECT_ID}/beef:latest'
